version: '3.8'

services:
  vulnerable-redis:
    build:
      context: ./vulnerable/redis
    volumes:
      - ./vulnerable/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./vulnerable/redis/data:/data
      - ./vulnerable/redis/logs:/var/log/redis
    networks:
      - vulnerable-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_LOGFILE=/var/log/redis/redis-dev.log
    restart: "no"
    profiles: ["vulnerable", "all"]
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  vulnerable-backend:
    build:
      context: ./vulnerable/backend
    depends_on:
      - vulnerable-redis
    networks:
      - vulnerable-network
    environment:
      - REDIS_HOST=vulnerable-redis
      - REDIS_PORT=6379
      - FLASK_ENV=development