global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'vulnerable-redis'
    static_configs:
      - targets: ['vulnerable-redis-exporter:9121']
    metrics_path: /metrics

  - job_name: 'secure-redis'
    static_configs:
      - targets: ['secure-redis-exporter:9121']
    metrics_path: /metrics
